### ISSUE TITLE
[Improvement]: Can we add docker compose watch for sync and rebuild?

### ISSUE THREAD

**Issue by patil-tejas** [code100x/job-board#153]
@VineeTagarwaL-code 

```yaml
develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
          
# But will have to remove these bind mounts as they wont let watch monitor the file path as it creates a bind mount
```yaml
volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
```  
### Following occurs , not letting monitor those files when using bind mounts
![image](https://github.com/user-attachments/assets/6840266f-e9b5-49a8-9029-4eb676bb21e2)
